### PR TITLE
fix: move unnecessary dependencies to devDependencies

### PR DESCRIPTION
**Pull request by fcastilloec**
I just received an alert for a vulnerability in my repositories and it's because this package was including `devDependencies` as `dependencies` that had those vulnerabilities.
This wouldn't PR only moves all dependencies to their proper place, so users of this package won't see these problems, in addition, it has the benefit of making the installation of this package less bloated.
The code only depends on `rimraf`, everything else is only used to build, lint, test and/or "protect" the code.

This PR doesn't fix any of the vulnerabilities found when running `npm audit` (9 vulnerabilities -4 low, 5 high- at the time of this PR), I leave that to @barinali to deal with any conflict (if any) when updating dependencies.

It's very ironic that the package that triggered the vulnerability warning was a dependency of `snyk` which is supposed to track and fix vulnerabilities 😀

### CODE REVIEW

**Comment by fcastilloec** [comment]
@barinali any chance we can get a new version pushed with these fixes?

**Comment by barinali** [comment]
Sure. I will publish a new version later today or tomorrow.

**Comment by barinali** [comment]
@fcastilloec I've just published v0.5.0. Could you please let me know if you encounter any problem with the new version?

**Comment by fcastilloec** [comment]
I just updated my project with your new version. All the previous reported vulnerabilities from your package are now gone. My `package-lock.json` changed a lot, many dependencies were removed, which is a great thing!
Thanks for the fast update!

**Pull request merged**
